/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BsIcon: typeof import('./components/BsIcon.vue')['default']
    GeminiChat: typeof import('./components/GeminiChat.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
  }
}
