/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthPage: typeof import('./components/AuthPage.vue')['default']
    BsIcon: typeof import('./components/BsIcon.vue')['default']
    ChatInterface: typeof import('./components/ChatInterface.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LandingPage: typeof import('./components/LandingPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
  }
}
